# /usr/local/nginx/conf/nginx.conf

worker_processes auto;
error_log /usr/local/nginx/logs/error.log;
pid /usr/local/nginx/logs/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log "pipe:rollback /usr/local/nginx/logs/access.log interval=1d baknum=3 maxsize=256M" main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    large_client_header_buffers 4 4k;
    client_max_body_size 80m;

    include /usr/local/nginx/conf/mime.types;
    default_type application/octet-stream;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      "";
    }

    upstream htmlparser {
        server 127.0.0.1:8001;
        server 127.0.0.1:8002;
        server 172.26.16.14:8001;
        server 172.26.16.14:8002;
        keepalive 32;
    }

    upstream zgetcontent {
        server 127.0.0.1:8101;
        server 127.0.0.1:8102;
        server 172.26.16.14:8101;
        server 172.26.16.14:8102;
        keepalive 32;
    }

    upstream xpathGet {
        server 127.0.0.1:8201;
        server 127.0.0.1:8202;
        server 127.0.0.1:8203;
        server 172.26.16.14:8201;
        server 172.26.16.14:8202;
        server 172.26.16.14:8203;
        keepalive 32;
    }

    server {
        listen       8000;              
        server_name  _;                 

        location / {
            proxy_pass http://htmlparser;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            # access_log off;
        }
    }

    server {
        listen       8100;
        server_name  _;

        location / {
            proxy_pass http://zgetcontent;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            # access_log off;
        }
    }
    server {
        listen       8200;
        server_name  _;

        location / {
            proxy_pass http://xpathGet;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            # access_log off;
        }
    }
}